### ISSUE TITLE
배경색 및 글번호등 툴바 기능 문의합니다.

### ISSUE THREAD

**Issue by pminmin2** [daumcorp/DaumEditor#422]
원하는대로 수정하여 게시판에 입혔는데요..
툴바 기능 거진 다 되는데 배경색, 글번호는 글보기할때 적용이 안되더라구요.

이해를 돕기위한 그림 올립니다.

![default](https://cloud.githubusercontent.com/assets/10083686/5870859/c7199cea-a318-11e4-8284-deeb63ccdebe.png)

그림과 같이 게시물을 작성할때 글번호, 배경색을 넣어서 작성하여 저장했습니다.
작성된 글을 보면 적용이 안되어있더라구요.

db에 저장된 내용을 볼때 글번호는 ol이라는 태그로 스타일이 먹혀있는걸 확인했습니다.
배경색도 여러건 저장해 보았습니다만, db에 저장될때 배경색에 대한 태그는 없더군요.

브라우저에서 완성된 소스에는 db에 저장된 태그 그대로 있더군요.
뭔가 빠진건지 궁금합니다.

추가로. 거의 완성단계인데
에디터에 첨부된 pages폴더의 파일및 폴더(trex 폴더의 html파일등)들은 삭제해도 되는건지 궁금하네요.

daumeditor-7.5.7 사용중입니다.

**Comment by k10526** [comment]
Editor.getContentWithBg() 이 메소드를 사용해 보시겠어요~

**Comment by pminmin2** [comment]
말씀하신 매소드로 적용해보니 백그라운드 컬러가 적용되긴 하네요.

하지만 번호매기기는 안되네요.
백그라운드 컬러는 본문영역 전체가 아니라 글을 작성한 글씨가 있는 영역만 되네용.
ㅠㅠ뭘빼먹은걸까요...ㅠㅠㅠㅠㅠㅠ

**Comment by k10526** [comment]
보기 페이지에서 content_view.css를 추가해 보시겠어요~

**Comment by pminmin2** [comment]
말씀하신대로 css 추가했습니다만, 별다른 변화는 없네요....

**Comment by k10526** [comment]
흠 콘솔창에서 element를 누르시면 어떤 css가 해당 style을 방해하는지 아실수 있으실꺼에요. 그부분을 수정해보시면 될듯합니다. 해당 이슈를 종료하겠습니다.
