### ISSUE TITLE
줄바꿈 관련 문의 드립니다.

### ISSUE THREAD

**Issue by seongmi** [daumcorp/DaumEditor#425]
다음에디터 최신버전 다운로드 받아 적용하였습니다.
적용하여 개발하고 보니,

첫번째.줄바꿈을 두 줄 이상 시 두 줄을 바꾸고 DB에 저장했지만 한줄만 개행된 상태로 출력이 되고 있습니다.

두번째. 어떤 단어를 작성후 아무런 키를 누르지 않은 채 단어를 복사하여 작성한 단어 끝에
커서를 위치한 후 붙여 넣기할 경우, 강제 개행이 되어 다음 행에 붙여 넣기가 되고 있는 상태입니다.

( 테스트해본 브라우저는 IE9, IE10, IE11입니다.)

바쁘시겠지만... 어떤 방법으로 해결할 수 있는지 꼭 좀 답변 부탁드립니다.

**Comment by ragiragi** [comment]
줄바꿈 이슈는 대게 `<p>` 에 대한 스타일(높이) 이슈가 많습니다. 게시글 조회 화면의 CSS inspect 해보시는 걸 추천합니다.

단어 복사시 줄바꿈 이슈는 단어를 하나만 작성하더라도 실제 마크업은 `<p>헬로우</p>` 와 같이 문단으로 감싸지게 되는데 브라우저에서 블럭선택시 range 가 위 `<p>` 포함하여 잡혀서 생기는 현상입니다. 브라우저별 range 로직에 따라 다르게 동작하는데 IE 브라우저에서 특히 그렇게 동작하네요. 브라우저 기본 동작 특성인지라 단기 수정은 힘들 것 같고, 향후 개편시 고려하도록 하겠습니다.

감사합니다.
