### ISSUE TITLE
쉬프트 엔터 <br> 태그 대신 <br />로 변경할 수 있나요?

### ISSUE THREAD

**Issue by gonzoora** [daumcorp/DaumEditor#426]
안녕하세요~

버전은 5.4.0.5842 입니다.

쉬프트 엔터를 치게 되면 'br'이 자동적으로 들어가는데요~

br 닫힘태그로 변경하고 싶습니다. br / 로요~~

개발페이지가 너무 많아서 일일이 replace시키기가 어려워서 문의드립니다.

가능여부가 궁금하고 방법을 알려주시면 감사하겠습니다 ^^

**Comment by k10526** [comment]
<br>은 쉬프트 엔터를 칠 경우 브라우저에서 기본적으로 추가되는 태그 입니다. 해당 방식을 변경하긴 어렵습니다. 저희쪽에서 추천드릴만한 방법은 작성이나 수정시에 완료 되었을때 replace를 하시는게 가장 나은 방법입니다.
