### ISSUE TITLE
에디터에서 사진 첨부시 팝업창 사이즈 조절 가능한가요?

### ISSUE THREAD

**Issue by perte** [daumcorp/DaumEditor#427]
제목 그대로 팝업창의 사이즈 조절이 가능한지요?
popup.js 파일을 열었다가 기겁을 해서요...도저히 찾을 엄두가 안 나네요...

pages/trex/image.html 파일에 <input type="file"> 형태로 파일을 추가했는데

팝업되는 창 자체가 너무 커서 사이즈 조절로 보기 좋게 맞추고 싶습니다.

가능한지요? 가능하다면 어디서 어떻게 설정해주면 되는지요...? 초보라 힘드네요 ㅠㅠ

도움 부탁드립니다(__)

**Comment by k10526** [comment]
new Editor 하실때 config값에
```
attacher:{
    //...
    image: {
        //...
        features:{left:left, top:top, width:width, height:height}
    }
}
```
left, top, width, height를 원하시는 데로 숫자를 넣고 하시면 됩니다.

**Comment by perte** [comment]
우선 답변 감사드립니다(__) 그런데 알려주신 방법을 어디다 입력해야할지 정확히 모르겠어요 ㅠㅠ 

제가 인터넷에서 블로그들 보면서 구현했던건데 방식이 어떤거냐하면요...
/pages/trex/image.html파일에 <input type="file">을 추가하고 form도 추가해서 action 값을
uploader.jsp라는 페이지로 주었고 uploader.jsp 소스에는 <body onload="initUploader();"> 로 
스크립트를 호출하는데 해당 스크립트는 다음과 같습니다.
==========================================================================
function initUploader()
{
	var _opener = PopupUtil.getOpener();
    if (!_opener) {
        alert('잘못된 경로로 접근하셨습니다.');
        return;
    }
    
    var _attacher = getAttacher('image', _opener);
    registerAction(_attacher);
        
        if (typeof(execAttach) == 'undefined') { //Virtual Function
        return;
    }
    
    var _mockdata = {
        'imageurl': '<%=realPath%>/<%=filename%>',
        'filename': '<%=filename%>',
        'filesize': <%=fileSize %>,
        'imagealign': 'C',
        'originalurl': '<%=realPath%>/<%=filename%>',
        'thumburl': '<%=realPath%>/<%=filename%>'
    };
    execAttach(_mockdata);
    closeWindow();
}
==========================================================================
저렇게하면 본문에 그림이 삽입은 됩니다....

말씀하신 new Editor(config)는 저의 경우 페이지가 열릴때만 한 번 있더군요...

새로운 창을 열 때 같으면 알려주신대로 new Editor(config) 전에 셋팅으로 해주면 되는 것 같은데

사진첨부는 에디터에 기본적으로 있는거라 어디서 해야할지 모르겠네요...

사진첨부하는 원본 소스 보면 <a href="javascript:;">로만 되어있으니....

번거로우시겠지만 답변 기다리겠습니다. 미리 감사드립니다(__)

**Comment by perte** [comment]
아...질문을 하나 더 올렸다가 해결했습니다. 무슨 뜻인지 제가 잘 이해 못했었는데 혹시 여기다 하는건가
싶어서 해보니 되네요 ㅎㅎ 답변 고맙습니다~
