### ISSUE TITLE
다음에디터 지원 관련 

### ISSUE THREAD

**Issue by rosy353** [daumcorp/DaumEditor#428]
다음에디터를 사용하려고 하는데 
지원운영체제와 지원 브라우저 및 버전을 알고 싶고
html5지원 브라우저와 미지원 브라우저의 업로드 차이도 알고 싶습니다.

**Comment by k10526** [comment]
지원 브라우져는 ie6이상입니다. 그러나 원할하게 사용하려면 ie8이상을 쓰셔야 합니다. 업로드는 저희쪽에서 구현되는 부분이 아니라 사용자분이 직접 구현해 주셔야 합니다. 시중에 있는 uploadify.js등 좋은 라이브러리를 사용하셔서 구현해주시면 됩니다.

**Comment by rosy353** [comment]
죄송하지만 하나만 더 질문 하자면 지원 운영체제는 윈도우 xp,7,8,vista mac 다 사용 가능하나요~?

**Comment by k10526** [comment]
네 다 지원 가능 합니다. ^^

**Comment by rosy353** [comment]
감사합니다 좋은 하루되세요!!^^
