### ISSUE TITLE
외부컨텐츠 항목 통해서 embed 태그 넣을 시

### ISSUE THREAD

**Issue by alldne** [daumcorp/DaumEditor#432]
안녕하세요

외부 컨텐츠 입력 기능을 통해 embed태그를 붙여넣었는데, 다음 에디터에서 embed 태그에 묵시적으로 width=0을 추가하는것으로 보입니다.

다음 데모에서도 동일 현상 재현되는것을 방금 확인하였습니다.
http://uie.daum.net/openeditor/sample/latest/editor.html

붙여넣은 embed 태그는 아래와 같은식이며 이미 width 값이 100%로 설정되어있습니다.
```
<embed width="100%" height="450" scrolling="no" frameborder="no" src="/path/to/resource">
```
의도된것인지 문의드립니다.
감사합니다.

**Comment by ragiragi** [comment]
embed 코드에 대한 preview image 삽입과정에서 `%` 단위를 제대로 인식하지 못해 생기는 문제인 듯 싶습니다.

https://github.com/daumcorp/DaumEditor/blob/63ee368b801a73efc91da5d12000ac6bacd68465/daumeditor/js/trex/embeder/media.js#L341

```
> "100%".parsePx() 
0
```

@k10526 검토 부탁드려요.

**Comment by k10526** [comment]
#c8704da

**Comment by k10526** [comment]
c1ae1aedf72881402145a045ba1a20e1b8ad9155
