### ISSUE TITLE
크롬 브라우저 이미지 리사이즈 문의

### ISSUE THREAD

**Issue by parknoeun** [daumcorp/DaumEditor#437]
데모에서는 이미지 리사이즈가 잘 되는데

데모 파일 받아서 소스 그대로 붙였는데 

돌리면 리사이즈가 안되더라구여

에디터 생성시 혹시 옵션이라던가.

이미지 추가시 추가 코드가 필요한가요?

에디터 버전은 7.4.1버전을 사용하고 있습니다.

**Comment by k10526** [comment]
이미지 리사이즈는 7.5이상 버전부터 가능합니다. ^^
