### ISSUE TITLE
다음에디터 로컬사용시 [외부컨텐츠 데이타삽입  오류-크롬]

### ISSUE THREAD

**Issue by uvbus** [daumcorp/DaumEditor#439]
[외부컨텐츠 데이타삽입  오류-크롬]
크롬으로  다음에디터를 로컬로 작업시 typeof(execEmbed)이  'undefined'으로 걸립니다.
외부컨텐츠가 입력되지않습니다. 어떻게 처리해야할까요?
(파이어폭스는 잘작동됩니다.)

daumeditor/pages/trex/tool/ASYNC/multimedia.html중에서
.....................
        // 코드 삽입 완료 후
	function done() {

		var _data = {};

		var types = document.getElementsByName("codeType");

		if (types[1].checked) {
			_data.url = document.getElementsByName("url")[0].value.trim();
		} else if (types[0].checked) {
			_data.code = document.getElementsByName("source")[0].value.trim();

		}
		if (typeof(execEmbed) == 'undefined') { //Virtual Function
       alert("test");
	        return;
	    }

		executeAfterDataCheck(_data, function(){
			execEmbed(_data);
			window.close();
	    }); 
	}
...........

**Comment by ragiragi** [comment]
다음에디터는 로컬(`file://`) 작업환경이 고려되어있지 않습니다.  로컬에도 서버 세팅 후(localhost) 사용하시길 부탁드립니다.
혹시 서버 세팅하여 사용 도중 문제가 발생하셨다면 좀 더 자세한 에러로그를 첨부해주시면 파악하는데 도움이 될 것 같습니다.
