### ISSUE TITLE
저장시 뜬금없이 textarea가 표시되는데 표시되지 않게 하는 방법은?

### ISSUE THREAD

**Issue by savour75** [daumcorp/DaumEditor#440]
![11211](https://cloud.githubusercontent.com/assets/11266435/6436628/7d8feace-c0f6-11e4-902c-930b3b19cc8c.gif)

글 저장시 위의 이미지에서 붉은색 사각형 표시의 textarea가 표시되는데 없애는 방법좀 알려주세요.

**Comment by k10526** [comment]
textarea에 display 속성을 none으로 주시면 됩니다.
