### ISSUE TITLE
다음에디터 로딩시 canvas 크기(높이) 조절 가능한가요?

### ISSUE THREAD

**Issue by shatine** [daumcorp/DaumEditor#442]
버전 7.5.9. 입니다.
1. 글의 내용을 입력하는 canvas 부분을 조금 작게 해서 생성하고 싶습니다.
어디를 수정해야 하는지 도움 부탁합니다.

2. 이미지 업로드시에 "용량을 초과하여 더이상 등록할 수 없습니다." 라는 에러 메세지가 나오고
이미지가 등록이 되지 않습니다. 근데 editor.html에서는 체크 하는 부분이 없더라구요...ㅠㅠ
attacher.js 에 보니 해당 메세지는 있던데, 도대체 어디서 호출을 하고 있는지 알 수가 없습니다.
용량은 3.6mb 이기 때문에 용량 때문은 아닌 듯 하고, 가로 세로 사이즈가 canvas 사이즈보다 
확연히 큽니다. 대략 4,000 * 3,000 정도의 사이즈 입니다.
이때문에 발생하는 메세지인지 용량 때문인지 명확하지는 않습니다.
메세지가 나오지 않고 이미지를 등록하려면 어떻게 해야 하는지요...
가령 강제로 이미지 사이즈만 canvas사이즈보다 작에 해서 보여줄 수는 없을까요?

**Comment by rosy353** [comment]
이미지 삽입은
var _mockdata = { 에다가 
'width' : '100',
'height' : '100',를 입력하면 크기는 조절되는데 용량체크는 따로 어디 존재하나요??
업로드 용량이 따로 정해져 있는 부분이 있나요?? 메세지도 뜨나요?? 헐헐..
없어서 새로 만들었는뎅.. 제가 못찾는 건가요?? 저도 알고 싶습니다!!

**Comment by shatine** [comment]
바보같은 질문인데요...ㅠㅠ
 
var _mockdata =  &lt;==== 이 부분이 어디에 있나요? 아무리 찾아도 없는데요...
 
그리고, 용량체크 에러는 그냥 무지 큰 이미지 파일 첨부 하니까 나는데요
버전이 저랑 틀리신건가요???

 
블로그서명님의블로그
자기소개가없습니다.
-----Original Message-----

**Comment by k10526** [comment]
new Editor하실때
config값을 변경해 주세요.
sidebar: {
		capacity: {
			maximum: 2097152//(파일 최대 크기)
		}
	}
