### ISSUE TITLE
다음에디터 표삽입시 

### ISSUE THREAD

**Issue by rosy353** [daumcorp/DaumEditor#443]
다음에디터 표 삽입시에는 글이 정상적으로 보이다가 
이제 db에 저장하고 불러오면 표위에 엄청난 공백이 생겨서 저장이 됩니다.
이거 어찌 처리해야되나요1?

**Comment by k10526** [comment]
불러올때 element에 넣은다음에 불러오지 마시고 문자열을 바로 넣어주세요.

**Comment by rosy353** [comment]
죄송한데 조금만 자세히 알려주세요. . . .

**Comment by k10526** [comment]
https://github.com/daumcorp/DaumEditor/blob/master/daumeditor/editor.html#L632
컨텐츠를 위 처럼 넣으신것 같은데요.
여기다가 바로 문자열로 넣어주세요.

**Comment by rosy353** [comment]
저런구문안쓰고  처리하면 알수있는방밥이없나요??
저장 될 때 잘못 저장되는 건가요??

**Comment by k10526** [comment]
보통 인풋이나 textarea로 넣는경우 예를 들자면 <input type='text' value=<%value%> /> 이렇게 넣게 되는데요. html에서 &nbsp;같은 요소를 스페이스로 치환한다거나 하는 작업을 선행하게 되죠. 이래서 문제가 발생하는데요. http://php.net/manual/kr/function.htmlspecialchars.php 이와 같은 메소드를 먼저 처리 하시고 넣으시던가 혹은 html에서 넣는게 아니라 아니면 자바스크립트로 <script>input.value = '<%%>';</script> 이렇게 넣어주시면 됩니다.
