### ISSUE TITLE
다음에디터 데이터 저장 관련

### ISSUE THREAD

**Issue by rosy353** [daumcorp/DaumEditor#445]
다음에디터에서 다른기능은 문제없이 저장되어 출력되는데 

유독 표만 넣으면 표 위로 공백이 생겨서 저장이 됩니다.

만약 표가 행과 열이 많으면 표 위 공백이 비례하여 크게 저장이 되어 출력됩니다.

저장되기 전에는 정상으로 보이다가 저장하고 다시 수정을 하면 

위와같은 증상이 나타납니다.

다른 소스는 http://php.net/manual/kr/function.htmlspecialchars.php와 비슷하고 제일 

아래 소스만 
	var config = {
		txHost: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) http://xxx.xxx.com */
		txPath: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) /xxx/xxx/ */
		txService: 'sample', /* 수정필요없음. */
		txProject: 'sample', /* 수정필요없음. 프로젝트가 여러개일 경우만 수정한다. */
		initializedId: "", /* 대부분의 경우에 빈문자열 */
		wrapper: "tx_trex_container", /* 에디터를 둘러싸고 있는 레이어 이름(에디터 컨테이너) */
		form: 'tx_editor_form'+"", /* 등록하기 위한 Form 이름 */
		txIconPath: "Daum_Editor/images/icon/editor/", /*에디터에 사용되는 이미지 디렉터리, 필요에 따라 수정한다. */
		txDecoPath: "/Daum_Editor/images/deco/contents/", /*본문에 사용되는 이미지 디렉터리, 서비스에서 사용할 때는 완성된 컨텐츠로 배포되기 위해 절대경로로 수정한다. */
		canvas: {
			styles: {
				color: "#123456", /* 기본 글자색 */
				fontFamily: "굴림", /* 기본 글자체 */
				fontSize: "10pt", /* 기본 글자크기 */
				backgroundColor: "#fff", /*기본 배경색 */
				lineHeight: "1.5", /*기본 줄간격 */
				padding: "8px" /* 위지윅 영역의 여백 */
			},
			showGuideArea: false
		},
		events: {
			preventUnload: false
		},
		sidebar: {
			attachbox: {
				show: true,
				confirmForDeleteAll: true
			}
		},
		size: {
			contentWidth: 700 /* 지정된 본문영역의 넓이가 있을 경우에 설정 */
		}
	};

	EditorJSLoader.ready(function(Editor) {
		var editor = new Editor(config);
	});
	
	function validForm(editor) {
		var frm = document.frm;
		
		var validator = new Trex.Validator();
		var content = editor.getContent();
		if (!validator.exists(content)) {
			alert('내용을 입력하세요');
			frm.contentchk.value="false";
			return false;
		}else{
	        var content = editor.getContent();

	        frm.content.value = content;
		}
	}
	Editor.modify({
		 "content":$tx('content')
	 });

이렇게 입력하였습니다.  조언좀 부탁드립니다.

**Comment by k10526** [comment]
```
Editor.modify({
     "content":$tx('content') -> <%스트링%>
 });
```
또는
```
<textarea id='content' ><%jsp이신지 php는 모르겠지만요 여기에서 &에 대해서 replace추가%>'></textarea>
```
해주시면 됩니다.

**Comment by rosy353** [comment]
아 감사합니다!!
