### ISSUE TITLE
본문 이미지삽입 관련

### ISSUE THREAD

**Issue by rosy353** [daumcorp/DaumEditor#447]
혹시 본문에 사진을 삽입했을때  개수 제한이 있거나 용량제한이 있나요?? 없다면 추가할수있는 방법을 알수 읺을까요??

**Comment by ragiragi** [comment]
전체 attachment size 총합에 대한 제약을 설정할 수 있습니다.

http://uie.daum.net/openeditor/api/draft/configuration.html#capacity
