### ISSUE TITLE
익스11 에서 글 등록시 값이 안넘어가는거같아요

### ISSUE THREAD

**Issue by hhs00** [daumcorp/DaumEditor#450]
현재쓰고있는버전은 7.3.19 입니다

글등록시 내용이 빈값으로 넘어가고있는데요

메타테그 IE=10 이렇게 해봐도 안되는데

익스플로러 호환성보기에 설정을해놓으면 값이 제대로 넘어가고있습니다

최신버전받아야지만 해결 가능할까요?

**Comment by rosy353** [comment]
에디터 안에쓴 contant 값 말하시는건가요??
