### ISSUE TITLE
탭키 관련 문의드립니다

### ISSUE THREAD

**Issue by gonzoora** [daumcorp/DaumEditor#451]
안녕하세요~

웹접근성 관련해서 문의드립니다.

다음에디터에서 탭키를 누르면 들여쓰기가 되고 빠져나오지 못하는데

이 기능을 쓰지 않고 빠져나와서 다른 버튼으로 갈수있게

할수있는지 할수있다면 어떻게 하면 되는지 문의드립니다

**Comment by ragiragi** [comment]
특정 단축키를 끄는 기능은 공식적으로 지원하지 않습니다만 config 수정을 통해 해결할 수는 있습니다.

```
    toolbar: {
      indent: {
        hotKey: {keyCode: -1}
      },
      outdent: {
        hotKey: {keyCode: -1}
      }
    },
```

공식 지원 사항은 아니기 때문에 향후 업데이트에 따라 변경될 수 있음을 참고바랍니다.
