### ISSUE TITLE
띄어쓰기가 물음표로 바뀝니다.

### ISSUE THREAD

**Issue by macho199** [daumcorp/DaumEditor#457]
editor버전 :7.4.27
브라우저 : ie11
개발환경 : asp, mysql

에디터에서 띄어쓰기를 하면 소스상에는 &amp;nbsp;로 찍히고 저장시 특수기호값으로 바뀌는지 물음표(?)로 저장됩니다. 그래서 DB상에 &amp;nbsp;로 직접 데이터를 넣은후 에디터에서 부르면 빈값(아마도 안보이는특수기호)으로 보여집니다.

띄어쓰기가 물음표로 바뀌는 현상을 없애고 싶습니다. 안된다면 &amp;nbsp;를 대체하는 특수기호값이라도 알려주시면 감사하겠습니다.

**Comment by ragiragi** [comment]
`&nbsp;` 는 정상적인 HTML 기호로서 다른 문자로의 대체 대상이 아닙니다. 
에디터 이슈가 아닌 서버 프로그램 - DB 저장 구간에 데이터 변환에 문제가 있는 것으로 예상됩니다.
