### ISSUE TITLE
수정상태에서 에디터 내부 객체의 이벤트 처리가 가능할까요?

### ISSUE THREAD

**Issue by flyup213** [daumcorp/DaumEditor#462]
별도로 버튼객체를 삽입하는 팝업창을 만들어서 사용중입니다.

삽입된 버튼을 더블클릭해서 팝업창을 다시 띄워야 하는데(수정) 에디터 외부? 함수를 호출하지 못하고 있어요.

버튼 삽입 시 ondblclick이벤트에 alert을 찍으니까 동작은 하는데.. 서로 영역이 다른가봅니다.

외부 영역의 함수를 호출할 수 있는 방법이 있을까요?

**Comment by k10526** [comment]
어떤 오류가 나는지 알려주세요 ^^ 콘솔에 찍힌 오류를 붙여넣기 해주셔도 됨니다.

**Comment by flyup213** [comment]
오류라기보다는
에디터를 사용하는 웹페이지에 정의된 함수를 호출하지 못하고 있습니다.
추가한 버튼의 ondblclick="alert(1);"은 동작을 하는데
페이지에 함수를 정의하고
function aa() {
    alert(2); 
}
추가한 버튼에 ondblclick="aa();" 은 aa함수를 찾을 수 없다고 합니다.

**Comment by flyup213** [comment]
해결되었습니다.
parent.aa()로 호출하니 되는군요.

**Comment by ragiragi** [comment]
@flyup213 현재 다음에디터는 편집영역이 iframe 으로 구성되어 있습니다. 참고바랍니다~
